### ISSUE TITLE
feat(site): update site content to avoid blatant "inaccurate information"

### ISSUE THREAD

**Issue by EnokiUN** [eludris/elusite#7] opened 2023-10-16 21:50 UTC
Modify the home page to include some actual features Eludris offers instead of old bogus

**Comment by Sharp-Eyes** [comment] 2023-10-16 21:52
no

**Comment by EnokiUN** [comment] 2023-10-16 21:52
> no

what

**Comment by Sharp-Eyes** [comment] 2023-10-16 21:54
Closed as intended behaviour.

**Comment by Sharp-Eyes** [comment] 2023-10-16 21:55
thanks eric

**Comment by EnokiUN** [comment] 2023-10-16 21:55
no please

**Comment by EnokiUN** [comment] 2023-10-16 21:56
I will play arknights if you close this again

**Comment by Sharp-Eyes** [comment] 2023-10-16 21:56
@everyone we are never closing this issue.

**Comment by EnokiUN** [comment] 2023-10-28 09:53
gtg play arknights

**Closed as completed** 2023-10-28 09:53 UTC
